export enum ENV {
  NODE_ENV = 'NODE_ENV',
  HOST = 'HOST',
  PORT = 'PORT',
  LOG_LEVEL = 'LOG_LEVEL',
  MONGO_DB_HOST = 'MONGO_DB_HOST',
  MONGO_DB_PORT = 'MONGO_DB_PORT',
  MONGO_DB_USER = 'MONGO_DB_USER',
  MONGO_DB_PASSWORD = 'MONGO_DB_PASSWORD',
  MONGO_DB_DATABASE = 'MONGO_DB_DATABASE',
  MONGO_DB_URL = 'MONGO_DB_URL',
  PASSWORD_SECRET = 'PASSWORD_SECRET',
  JWT_SECRET = 'JWT_SECRET',
}
